[package]
name = "libdqg"
version = "0.1.0"
edition = "2024"

[dependencies]
pollster = "1.0.1"
wgpu = "30.0.0"
winit = "0.30.13"
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg"]}
glam = "0.33.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.60", features = ["Win32_Graphics_Dwm", "Win32_Foundation"] }
