[package]
name = "editor"
version = "0.1.0"
edition = "2024"

[dependencies]
libdqg = { path = "../core" }
wgpu = "30.0.0"
winit = "0.30.13"
egui = "0.36.2"
egui-wgpu = "0.36.2"
egui-winit = "0.36.2"
serde = { version = "1", features = ["derive"] }
ron = "0.8"
rfd = "0.15"
anyhow = "1.0"
image = "0.25"

[build-dependencies]
libdqg = { path = "../core" }
